In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('data/Data.csv')

Features are columns with whihc we predict dependent variables.

Dependant variables are values that need to be predicted using a machine learning algorithm.

In [3]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

<i> dataset.iloc[[1]] </i>

  --> returns a dataframe

<i> dataset.iloc[1] </i>

  --> returns a series

<i> remove columns from the data set using the iloc method from dataframe objects </i>

In [4]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Taking care of missing data

<i> Create an imputer object of class SimpleImputer and use fit and transform methods to take care of missing data </i>

from sklearn.impute import SimpleImputer  

In [6]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

# Encoding categorical variables

One hote encoding

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [22]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
ohe = OneHotEncoder()

In [23]:
X = np.array(ct.fit_transform(X))

In [24]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [28]:
columns = ['France', 'Germany', 'Brazil', 'Age', 'Salary']
features = pd.DataFrame(X, columns=columns)

In [29]:
features

France Germany Brazil      Age   Salary
0      1       0      0       44    72000
1      0       0      1       27    48000
2      0       1      0       30    54000
3      0       0      1       38    61000
4      0       1      0       40  63777.8
5      1       0      0       35    58000
6      0       0      1  38.7778    52000
7      1       0      0       48    79000
8      0       1      0       50    83000
9      1       0      0       37    67000

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [38]:
features_array = features.values

In [41]:
features_array

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

# Splitting dataset into train and test

feature scaling should be done AFTER train test split so as to avoid information leakage from test data to train data when taking mean of the features for scaling.

In [46]:
from sklearn.model_selection import train_test_split

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [49]:
X_train.shape

(8, 5)

In [50]:
X_test.shape

(2, 5)

# Feature scaling

standardisation and normalisation <br>
do not apply scaling to dummy varibales (one hot encoding categories) 

In [53]:
from sklearn.preprocessing import StandardScaler

In [58]:
s_scaler = StandardScaler()
X_train[:,3:] = s_scaler.fit_transform(X_train[:,3:])
X_test[:,3:] = s_scaler.transform(X_test[:,3:])

In [60]:
print(X_train)
print('\n')
print(X_test)

[[0.0 0.0 1.0 -0.19159184384578554 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057846 -0.07013167641635404]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022487 -0.307866172742979]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
